In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [20]:
def generate_spiral_order(n):
  matrix = [[0]*n for _ in range(n)]
  num =1
  top, bottom= 0, n-1
  left, right= 0, n-1

  while top<=bottom and left<=right:
    for col in range(left, right+1):
      matrix[top][col] = num
      num +=1
    top +=1

    for row in range(top, bottom+1):
      matrix[row][right] = num
      num +=1
    right -=1

    for col in range(right, left-1, -1):
      matrix[bottom][col] = num
      num +=1
    bottom -=1

    for row in range(bottom, top-1, -1):
      matrix[row][left] = num
      num +=1
    left +=1

  return matrix

output = np.array(generate_spiral_order(4))
print(output)

[[ 1  2  3  4]
 [12 13 14  5]
 [11 16 15  6]
 [10  9  8  7]]
